# Generated by Django 3.1.4 on 2020-12-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echo',
            name='message',
        ),
        migrations.AddField(
            model_name='echo',
            name='courseCredit',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='echo',
            name='courseDescription',
            field=models.CharField(default='etc', max_length=100),
        ),
        migrations.AddField(
            model_name='echo',
            name='courseID',
            field=models.CharField(default='ENSF 607', max_length=10),
        ),
        migrations.AddField(
            model_name='echo',
            name='courseName',
            field=models.CharField(default='random course', max_length=40),
        ),
        migrations.AddField(
            model_name='echo',
            name='hours',
            field=models.CharField(default='6', max_length=1),
        ),
        migrations.AddField(
            model_name='echo',
            name='learningOutcomes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='echo',
            name='reference',
            field=models.CharField(default='etc', max_length=100),
        ),
    ]
