# Generated by Django 3.1.4 on 2020-12-17 21:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201217_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='gradeComponents',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='echo',
            name='letterGrades',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
