# Generated by Django 3.1.4 on 2020-12-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201217_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutline',
            name='gradeComponents',
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='learningOutcomes',
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='letterGrades',
        ),
    ]
